# Generated by Django 3.2.9 on 2021-11-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_postcomment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='parent',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
