# Generated by Django 3.2.9 on 2021-11-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_postcomment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='comment',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
