# Generated by Django 3.2.9 on 2021-11-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_postcomment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='reply_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
