# Generated by Django 3.2.7 on 2021-11-16 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_product_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
