# Generated by Django 3.2.7 on 2021-11-16 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0014_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('product_image', models.ImageField(blank=True, default='product_img/cute.jfif', null=True, upload_to='product_img/')),
                ('weight', models.IntegerField(null=True)),
                ('price', models.IntegerField(null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 11, 16, 16, 28, 30, 329925))),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
